import type { Language } from "@/i18n/translations";

const PT_TO_EN_EXACT: Record<string, string> = {
  "Valor Total Pendente": "Total Outstanding Amount",
  "VALOR TOTAL PENDENTE": "TOTAL OUTSTANDING AMOUNT",
  "Valor Total Pago": "Total Paid Amount",
  "VALOR TOTAL PAGO": "TOTAL PAID AMOUNT",
  "Percentual de Faturas Pendentes (Valor)": "Outstanding Invoices Percentage (Value)",
  "PERCENTUAL DE FATURAS PENDENTES (VALOR)": "OUTSTANDING INVOICES PERCENTAGE (VALUE)",
  "Número de Faturas Pendentes": "Number of Outstanding Invoices",
  "NÚMERO DE FATURAS PENDENTES": "NUMBER OF OUTSTANDING INVOICES",
  "Número de Faturas Pagas": "Number of Paid Invoices",
  "NÚMERO DE FATURAS PAGAS": "NUMBER OF PAID INVOICES",
  "Distribuição do Valor Total por Status da Fatura": "Total Amount Distribution by Invoice Status",
  "Quantidade de Faturas por Status": "Invoice Count by Status",
  "Pendente": "Outstanding",
  "Pago": "Paid",
  "Paga": "Paid",
  "Pagas": "Paid",
  "Pendentes": "Outstanding",
  "Forte": "Strong",
  "Moderada": "Moderate",
  "Fraca": "Weak",
  "Forças": "Strengths",
  "Fraquezas": "Weaknesses",
  "Oportunidades": "Opportunities",
  "Oportunidade": "Opportunity",
  "Riscos": "Risks",
  "Ameaças": "Threats",
  "Padrões": "Patterns",
  "Padrão": "Pattern",
  "Recomendações": "Recommendations",
  "Recomendação": "Recommendation",
  "Plano de Ação": "Action Plan",
  "Curto Prazo": "Short Term",
  "Médio Prazo": "Medium Term",
  "Longo Prazo": "Long Term",
  "Crescimento": "Growth",
  "Eficiência": "Efficiency",
  "Risco": "Risk",
};

const PT_TO_EN_PHRASES: Array<[RegExp, string]> = [
  [/\bEntrar em contato\b/gi, "Contact"],
  [/\bentre em contato\b/gi, "contact"],
  [/\bentrar em contato\b/gi, "contact"],
  [/\bimediatamente\b/gi, "immediately"],
  [/\btodos os\b/gi, "all"],
  [/\btodas as\b/gi, "all"],
  [/\bcom\b/gi, "with"],
  [/\bpara\b/gi, "to"],
  [/\bpor meio de\b/gi, "through"],
  [/\bmeio de\b/gi, "through"],
  [/\bdireta e eficaz\b/gi, "direct and effective"],
  [/\bdo\b/gi, "of"],
  [/\bda\b/gi, "of"],
  [/\bdos\b/gi, "of"],
  [/\bdas\b/gi, "of"],
  [/\bum\b/gi, "a"],
  [/\buma\b/gi, "a"],
  [/\bo\b/gi, "the"],
  [/\ba\b/gi, "the"],
  [/\bos\b/gi, "the"],
  [/\bas\b/gi, "the"],
  [/\be\b/gi, "and"],
  [/\bou\b/gi, "or"],
  [/\bno\b/gi, "in the"],
  [/\bna\b/gi, "in the"],
  [/\bnos\b/gi, "in the"],
  [/\bnas\b/gi, "in the"],
  [/\bem\b/gi, "in"],
  [/\bpor\b/gi, "by"],
  [/\bValor Total Pendente\b/gi, "Total Outstanding Amount"],
  [/\bValor Total Pago\b/gi, "Total Paid Amount"],
  [/\bPercentual de Faturas Pendentes\b/gi, "Outstanding Invoices Percentage"],
  [/\bNúmero de Faturas Pendentes\b/gi, "Number of Outstanding Invoices"],
  [/\bNúmero de Faturas Pagas\b/gi, "Number of Paid Invoices"],
  [/\bfaturas pendentes\b/gi, "outstanding invoices"],
  [/\bfatura pendente\b/gi, "outstanding invoice"],
  [/\bfaturas pagas\b/gi, "paid invoices"],
  [/\bfatura paga\b/gi, "paid invoice"],
  [/\bfaturas vencidas\b/gi, "overdue invoices"],
  [/\bfatura vencida\b/gi, "overdue invoice"],
  [/\bvalor total analisado\b/gi, "total analyzed amount"],
  [/\bvalor total\b/gi, "total amount"],
  [/\bsaldo pendente\b/gi, "outstanding balance"],
  [/\bsaldo pago\b/gi, "paid balance"],
  [/\binadimplência\b/gi, "delinquency"],
  [/\binadimplentes\b/gi, "delinquent accounts"],
  [/\bpagamentos confirmados\b/gi, "confirmed payments"],
  [/\brecebimentos\b/gi, "collections received"],
  [/\breceita\b/gi, "revenue"],
  [/\bliquidez\b/gi, "liquidity"],
  [/\bfluxo de caixa\b/gi, "cash flow"],
  [/\bsaúde financeira\b/gi, "financial health"],
  [/\bexposição financeira\b/gi, "financial exposure"],
  [/\bpressão financeira\b/gi, "financial pressure"],
  [/\bprocesso de cobrança\b/gi, "collections process"],
  [/\brégua de cobrança\b/gi, "collections cadence"],
  [/\bpolítica de cobrança\b/gi, "collections policy"],
  [/\brotina de cobrança\b/gi, "collections routine"],
  [/\bequipe de finanças\/cobrança\b/gi, "finance/collections team"],
  [/\bequipe financeira\b/gi, "finance team"],
  [/\bequipe de cobrança\b/gi, "collections team"],
  [/\bcarga de trabalho\b/gi, "workload"],
  [/\besforço manual\b/gi, "manual effort"],
  [/\bclientes\b/gi, "customers"],
  [/\bcliente\b/gi, "customer"],
  [/\bcontas a receber\b/gi, "accounts receivable"],
  [/\bvencimentos\b/gi, "due dates"],
  [/\bvencimento\b/gi, "due date"],
  [/\batraso\b/gi, "late payment"],
  [/\batrasos\b/gi, "late payments"],
  [/\bcobrança\b/gi, "collections"],
  [/\bcobranças\b/gi, "collections"],
  [/\bfaturamento\b/gi, "billing"],
  [/\bfatura\b/gi, "invoice"],
  [/\bfaturas\b/gi, "invoices"],
  [/\bvalores\b/gi, "amounts"],
  [/\bvalor\b/gi, "amount"],
  [/\bstatus\b/gi, "status"],
  [/\bdados financeiros\b/gi, "financial data"],
  [/\bbase de dados\b/gi, "dataset"],
  [/\bbase\b/gi, "dataset"],
  [/\bdados\b/gi, "data"],
  [/\bconcentração significativa\b/gi, "significant concentration"],
  [/\bconcentração\b/gi, "concentration"],
  [/\boportunidade clara\b/gi, "clear opportunity"],
  [/\boportunidades\b/gi, "opportunities"],
  [/\boportunidade\b/gi, "opportunity"],
  [/\briscos\b/gi, "risks"],
  [/\brisco\b/gi, "risk"],
  [/\bpadrões\b/gi, "patterns"],
  [/\bpadrão\b/gi, "pattern"],
  [/\brecomendações\b/gi, "recommendations"],
  [/\brecomendação\b/gi, "recommendation"],
  [/\bplano de ação\b/gi, "action plan"],
  [/\bcurto prazo\b/gi, "short term"],
  [/\bmédio prazo\b/gi, "medium term"],
  [/\blongo prazo\b/gi, "long term"],
  [/\bação imediata\b/gi, "immediate action"],
  [/\bações imediatas\b/gi, "immediate actions"],
  [/\bações corretivas\b/gi, "corrective actions"],
  [/\bmedidas preventivas\b/gi, "preventive measures"],
  [/\botimizar\b/gi, "optimize"],
  [/\botimização\b/gi, "optimization"],
  [/\bimplementar\b/gi, "implement"],
  [/\bimplantação\b/gi, "implementation"],
  [/\bautomatizar\b/gi, "automate"],
  [/\bautomação\b/gi, "automation"],
  [/\bpriorizar\b/gi, "prioritize"],
  [/\bpriorização\b/gi, "prioritization"],
  [/\bmonitorar\b/gi, "monitor"],
  [/\bmonitoramento\b/gi, "monitoring"],
  [/\bacompanhar\b/gi, "track"],
  [/\bacompanhamento\b/gi, "monitoring"],
  [/\bsegmentar\b/gi, "segment"],
  [/\bsegmentação\b/gi, "segmentation"],
  [/\bnegociar\b/gi, "negotiate"],
  [/\bnegociação\b/gi, "negotiation"],
  [/\brenegociar\b/gi, "renegotiate"],
  [/\brenegociação\b/gi, "renegotiation"],
  [/\breduzir\b/gi, "reduce"],
  [/\bredução\b/gi, "reduction"],
  [/\baumentar\b/gi, "increase"],
  [/\bmelhorar\b/gi, "improve"],
  [/\bmelhoria\b/gi, "improvement"],
  [/\bestabelecer\b/gi, "establish"],
  [/\bdefinir\b/gi, "define"],
  [/\bcriar\b/gi, "create"],
  [/\bcrie\b/gi, "create"],
  [/\bdesenvolver\b/gi, "develop"],
  [/\banalisar\b/gi, "analyze"],
  [/\banalise\b/gi, "analyze"],
  [/\benviar\b/gi, "send"],
  [/\blembretes\b/gi, "reminders"],
  [/\balertas\b/gi, "alerts"],
  [/\bnotificações\b/gi, "notifications"],
  [/\bcomunicação\b/gi, "communication"],
  [/\brelatórios\b/gi, "reports"],
  [/\breports periódicos\b/gi, "periodic reports"],
  [/\bperiódicos\b/gi, "periodic"],
  [/\bindicadores\b/gi, "indicators"],
  [/\bmétricas\b/gi, "metrics"],
  [/\bdashboard\b/gi, "dashboard"],
  [/\bresponsáveis\b/gi, "owners"],
  [/\bprazos\b/gi, "deadlines"],
  [/\bprazo\b/gi, "deadline"],
  [/\bhistórico\b/gi, "history"],
  [/\btendências\b/gi, "trends"],
  [/\bpontualidade\b/gi, "payment timeliness"],
  [/\bpagamentos\b/gi, "payments"],
  [/\bpagamento\b/gi, "payment"],
  [/\bantecipado\b/gi, "early"],
  [/\bpontual\b/gi, "on-time"],
  [/\bincentivos\b/gi, "incentives"],
  [/\bconsiderar\b/gi, "consider"],
  [/\bconsidere\b/gi, "consider"],
  [/\brecuperação\b/gi, "recovery"],
  [/\bmaximizar\b/gi, "maximize"],
  [/\bimpacto\b/gi, "impact"],
  [/\bvisualizar\b/gi, "view"],
  [/\btempo real\b/gi, "real time"],
  [/\bavaliar\b/gi, "evaluate"],
  [/\beficácia\b/gi, "effectiveness"],
  [/\bajustar\b/gi, "adjust"],
  [/\bfeedback\b/gi, "feedback"],
  [/\btaxas\b/gi, "rates"],
  [/\btaxa\b/gi, "rate"],
  [/\brevisar\b/gi, "review"],
  [/\bpolíticas\b/gi, "policies"],
  [/\bpolítica\b/gi, "policy"],
  [/\bcrédito\b/gi, "credit"],
  [/\bnovos\b/gi, "new"],
  [/\bnovo\b/gi, "new"],
  [/\bintegrar\b/gi, "integrate"],
  [/\bsistema\b/gi, "system"],
  [/\bvisão 360\b/gi, "360-degree view"],
  [/\bpersonalizar\b/gi, "personalize"],
  [/\bexplorar\b/gi, "explore"],
  [/\bpossibilidade\b/gi, "possibility"],
  [/\boferecer\b/gi, "offer"],
  [/\bopções\b/gi, "options"],
  [/\bflexíveis\b/gi, "flexible"],
  [/\binvestir\b/gi, "invest"],
  [/\btreinamento\b/gi, "training"],
  [/\batendimento\b/gi, "support"],
  [/\blidar\b/gi, "handle"],
  [/\brelacionamento\b/gi, "relationship"],
  [/\bbom\b/gi, "good"],
  [/\bmanter\b/gi, "maintain"],
  [/\bobjeções\b/gi, "objections"],
  [/\bsoluções\b/gi, "solutions"],
  [/\brazões\b/gi, "reasons"],
  [/\bentender\b/gi, "understand"],
  [/\bindividualmente\b/gi, "individually"],
  [/\balto\b/gi, "high"],
  [/\balta\b/gi, "high"],
  [/\bmaior\b/gi, "higher"],
  [/\bmenor\b/gi, "lower"],
  [/\bmaioria\b/gi, "most"],
  [/\bperda\b/gi, "loss"],
  [/\bsignificativa\b/gi, "significant"],
  [/\bsignificativo\b/gi, "significant"],
  [/\bprolongada\b/gi, "prolonged"],
  [/\bprolongado\b/gi, "prolonged"],
  [/\bafetando\b/gi, "affecting"],
  [/\bempresa\b/gi, "company"],
  [/\bcomprometimento\b/gi, "impairment"],
  [/\bdificultando\b/gi, "making it harder"],
  [/\bplanejamento\b/gi, "planning"],
  [/\bexecução\b/gi, "execution"],
  [/\binvestimentos\b/gi, "investments"],
  [/\bdespesas operacionais\b/gi, "operating expenses"],
  [/\bdano\b/gi, "damage"],
  [/\bineficientes\b/gi, "inefficient"],
  [/\btardios\b/gi, "late"],
  [/\bapenas\b/gi, "only"],
  [/\bregistrada\b/gi, "registered"],
  [/\bregistrado\b/gi, "registered"],
  [/\bpermitindo\b/gi, "allowing"],
  [/\bprofunda\b/gi, "deep"],
  [/\bindividual\b/gi, "individual"],
  [/\bleve\b/gi, "slight"],
  [/\bao longo do ano\b/gi, "throughout the year"],
  [/\bdistribuição\b/gi, "distribution"],
  [/\bimpactando\b/gi, "impacting"],
  [/\bprojetado\b/gi, "projected"],
  [/\bexpressivo\b/gi, "substantial"],
  [/\bsuperando\b/gi, "exceeding"],
  [/\bconsideravelmente maior que\b/gi, "considerably higher than"],
  [/\brepresentando\b/gi, "representing"],
  [/\bé superior ao número de\b/gi, "is higher than the number of"],
  [/\bmaior volume significativo\b/gi, "highest significant volume"],
  [/\bvolume significativo\b/gi, "significant volume"],
  [/\bvolume pendente\b/gi, "outstanding volume"],
  [/\bmaior participação\b/gi, "higher share"],
  [/\bparticipação\b/gi, "share"],
  [/\bindicando\b/gi, "indicating"],
  [/\bpicos de risco\b/gi, "risk peaks"],
  [/\bpicos de vencimento\b/gi, "due-date peaks"],
  [/\babordagens personalizadas\b/gi, "personalized approaches"],
  [/\babordagem personalizada\b/gi, "personalized approach"],
  [/\buniformidade\b/gi, "uniformity"],
  [/\bsobrecarregar\b/gi, "overload"],
  [/\bsobrecarga\b/gi, "overload"],
  [/\bperíodos\b/gi, "periods"],
  [/\bmenos demandados\b/gi, "less demanding"],
  [/\breativo\b/gi, "reactive"],
  [/\bproativo\b/gi, "proactive"],
  [/\blembretes eficazes\b/gi, "effective reminders"],
  [/\bpróximas ao vencimento\b/gi, "near due date"],
  [/\bjá vencidas\b/gi, "already overdue"],
  [/\bdevido a\b/gi, "due to"],
  [/\bmaio\b/gi, "May"],
  [/\bmarço\b/gi, "March"],
  [/\bjaneiro\b/gi, "January"],
  [/\bfevereiro\b/gi, "February"],
  [/\babril\b/gi, "April"],
  [/\bjunho\b/gi, "June"],
  [/\bjulho\b/gi, "July"],
  [/\bagosto\b/gi, "August"],
  [/\bsetembro\b/gi, "September"],
  [/\boutubro\b/gi, "October"],
  [/\bnovembro\b/gi, "November"],
  [/\bdezembro\b/gi, "December"],
];

const PT_SENTENCES_TO_EN: Record<string, string> = {
  "A análise dos dados financeiros revela uma concentração significativa de faturas pendentes, impactando o fluxo de caixa projetado. O valor total de faturas pendentes é expressivo, superando as faturas pagas. Há uma oportunidade clara para otimizar o processo de cobrança e acompanhamento, especialmente considerando a distribuição dos vencimentos ao longo do tempo.":
    "The financial data analysis reveals a significant concentration of outstanding invoices, impacting projected cash flow. The total outstanding invoice amount is substantial and exceeds paid invoices. There is a clear opportunity to optimize the collections and monitoring process, especially considering the distribution of due dates over time.",
  "O Valor Total Pendente de faturas (R$ 17.800) é consideravelmente maior que o Valor Total Pago (R$ 8.300), representando 68% do valor total analisado.":
    "The Total Outstanding Amount for invoices (R$ 17,800) is considerably higher than the Total Paid Amount (R$ 8,300), representing 68% of the total analyzed amount.",
  "O número de faturas pendentes (8) é superior ao número de faturas pagas (3).":
    "The number of outstanding invoices (8) is higher than the number of paid invoices (3).",
  "Março e Maio de 2026 apresentam um volume significativo de faturas pendentes, indicando picos de risco de atraso.":
    "March and May 2026 show a significant volume of outstanding invoices, indicating late-payment risk peaks.",
  "A concentração de faturas pendentes em um número limitado de clientes pode indicar a necessidade de abordagens de cobrança personalizadas.":
    "The concentration of outstanding invoices among a limited number of customers may indicate the need for personalized collections approaches.",
  "A uniformidade dos vencimentos pode sobrecarregar a equipe em certos períodos, enquanto outros são menos demandados.":
    "The uniformity of due dates may overload the team during certain periods while others are less demanding.",
  "Processo de cobrança reativo, em vez de proativo, resultando em altas taxas de faturas pendentes.":
    "Reactive collections process instead of a proactive one, resulting in high outstanding-invoice rates.",
  "Possível falta de comunicação ou lembretes eficazes para clientes com faturas próximas ao vencimento ou já vencidas.":
    "Possible lack of communication or effective reminders for customers with invoices near due date or already overdue.",
  "Carga de trabalho desigual para a equipe de finanças/cobrança devido a picos de vencimento.":
    "Uneven workload for the finance/collections team due to due-date peaks.",
  "Implementar um sistema automatizado de lembretes de vencimento para reduzir o volume de faturas pendentes.":
    "Implement an automated due-date reminder system to reduce the volume of outstanding invoices.",
  "Desenvolver uma estratégia de segmentação de clientes para priorizar o acompanhamento de faturas de maior valor.":
    "Develop a customer segmentation strategy to prioritize monitoring of higher-value invoices.",
  "Analisar o histórico de pagamentos de clientes específicos para identificar padrões e ajustar as políticas de crédito ou termos de pagamento.":
    "Analyze the payment history of specific customers to identify patterns and adjust credit policies or payment terms.",
  "Perda de receita significativa devido à inadimplência prolongada, afetando a saúde financeira da empresa.":
    "Significant revenue loss due to prolonged delinquency, affecting the company's financial health.",
  "Comprometimento do fluxo de caixa, dificultando o planejamento e a execução de investimentos ou despesas operacionais.":
    "Cash-flow impairment, making it harder to plan and execute investments or operating expenses.",
  "Dano ao relacionamento com o cliente devido a processos de cobrança ineficientes ou tardios.":
    "Damage to customer relationships due to inefficient or late collections processes.",
  "A maioria dos clientes tem faturas de valores entre R$ 1.700 e R$ 3.500.":
    "Most customers have invoices ranging from R$ 1,700 to R$ 3,500.",
  "Há um padrão de vencimentos distribuídos ao longo do ano, com uma leve concentração entre Março e Maio.":
    "There is a pattern of due dates distributed throughout the year, with a slight concentration between March and May.",
  "A maioria dos clientes analisados tem apenas uma fatura registrada, não permitindo uma análise profunda de histórico individual.":
    "Most analyzed customers have only one registered invoice, which does not allow a deep analysis of individual history.",
  "Entrar em contato imediatamente com todos os clientes com faturas pendentes para negociar o pagamento.":
    "Contact all customers with outstanding invoices immediately to negotiate payment.",
  "Implementar um sistema básico de lembretes por e-mail 7 dias antes do vencimento e no dia do vencimento.":
    "Implement a basic email reminder system 7 days before the due date and on the due date.",
  "Priorizar a cobrança das faturas de maior valor pendente para maximizar o impacto no fluxo de caixa.":
    "Prioritize collections for invoices with the highest outstanding amount to maximize cash-flow impact.",
  "Desenvolver um dashboard de monitoramento de faturas para visualizar em tempo real o status e os valores.":
    "Develop an invoice monitoring dashboard to view status and amounts in real time.",
  "Avaliar a eficácia dos lembretes e ajustar a comunicação com base no feedback dos clientes e nas taxas de pagamento.":
    "Evaluate reminder effectiveness and adjust communication based on customer feedback and payment rates.",
  "Revisar as políticas de prazo de pagamento e crédito para novos clientes com base nos dados de inadimplência.":
    "Review payment-term and credit policies for new customers based on delinquency data.",
  "Integrar o processo de cobrança com o sistema de CRM para ter uma visão 360 do cliente e personalizar abordagens.":
    "Integrate the collections process with the CRM system to get a 360-degree customer view and personalize approaches.",
  "Explorar a possibilidade de oferecer opções de pagamento flexíveis para clientes com histórico de bom pagador.":
    "Explore offering flexible payment options to customers with a history of good payment behavior.",
  "Investir em treinamento da equipe de atendimento para lidar com objeções de cobrança e manter um bom relacionamento com o cliente.":
    "Invest in support team training to handle collections objections and maintain good customer relationships.",
  "Priorize a recuperação dos R$ 17.800 em faturas pendentes por meio de comunicação direta e eficaz.":
    "Prioritize recovery of the R$ 17,800 in outstanding invoices through direct and effective communication.",
  "Automatize os lembretes de vencimento e pós-vencimento para reduzir a carga de trabalho manual e melhorar a pontualidade dos pagamentos.":
    "Automate due-date and post-due-date reminders to reduce manual workload and improve payment timeliness.",
  "Analise individualmente os clientes com faturas pendentes de alto valor para entender as razões do atraso e negociar soluções.":
    "Analyze customers with high-value outstanding invoices individually to understand late-payment reasons and negotiate solutions.",
  "Crie relatórios periódicos de aging de faturas para monitorar a saúde financeira e identificar tendências de inadimplência.":
    "Create periodic invoice aging reports to monitor financial health and identify delinquency trends.",
  "Considere a implementação de incentivos para pagamento antecipado ou pontual para melhorar o fluxo de caixa.":
    "Consider implementing incentives for early or on-time payment to improve cash flow.",
  "Implementar uma rotina de cobrança proativa para clientes com faturas próximas ao vencimento.":
    "Implement a proactive collections routine for customers with invoices near due date.",
  "Automatizar lembretes de vencimento e alertas para faturas vencidas.":
    "Automate due-date reminders and alerts for overdue invoices.",
  "Priorizar a cobrança das faturas de maior valor pendente.":
    "Prioritize collections for invoices with the highest outstanding amount.",
  "Segmentar clientes por risco e valor pendente para definir abordagens personalizadas.":
    "Segment customers by risk and outstanding amount to define personalized approaches.",
  "Monitorar semanalmente o saldo pendente e a evolução dos pagamentos.":
    "Monitor outstanding balance and payment progress weekly.",
  "Criar indicadores de acompanhamento para reduzir a inadimplência.":
    "Create monitoring indicators to reduce delinquency.",
  "Negociar condições de pagamento com clientes de maior risco.":
    "Negotiate payment terms with higher-risk customers.",
  "Revisar a política de crédito e cobrança para reduzir novas pendências.":
    "Review credit and collections policies to reduce new outstanding invoices.",
  "Aumentar a previsibilidade do fluxo de caixa com acompanhamento contínuo dos vencimentos.":
    "Increase cash-flow predictability through continuous monitoring of due dates.",
  "Reduzir o volume de faturas pendentes com ações de cobrança segmentadas.":
    "Reduce the volume of outstanding invoices with segmented collections actions.",
};

export function localizeAnalysisText(value: string, language: Language) {
  if (language !== "en") return value;
  const trimmed = value.trim();
  if (PT_TO_EN_EXACT[trimmed]) return PT_TO_EN_EXACT[trimmed];
  if (PT_SENTENCES_TO_EN[trimmed]) return PT_SENTENCES_TO_EN[trimmed];

  return PT_TO_EN_PHRASES.reduce((text, [pattern, replacement]) => {
    return text.replace(pattern, replacement);
  }, value);
}

export function localizeAnalysisValue<T>(value: T, language: Language): T {
  if (language !== "en") return value;

  if (typeof value === "string") {
    return localizeAnalysisText(value, language) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => localizeAnalysisValue(item, language)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, localizeAnalysisValue(entry, language)])
    ) as T;
  }

  return value;
}
